language: c

os:
    - linux
    - osx

addons:
    apt:
      packages:
        - openssl

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew update
        brew install openssl
    fi

script:
    - vsafe test
